name: Test API Service on PR

on:
  pull_request:
    paths:
      - "packages/backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: |
          cd packages/backend
          pip install -r requirements.txt

      - name: Create ENV File
        run: |
          cd packages/backend/app
          echo "${{ secrets.ENV_API_TEST }}" > .env.test
          echo "${{ secrets.FIREBASE_ADMIN_SDK_SA_TEST }}" | base64 -d > "${{ secrets.FIREBASE_ADMIN_SDK_SA_FILENAME_TEST }}"

      - name: Run Tests
        run: |
          cd packages/backend
          pytest -s -vv app/tests
