name: GitHub Actions Demo 22222
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          
      - name: Create ENV File
        run: |
          echo "${{ secrets.BE_ENV_TEST }}" > .env.test
          
      - name: Create SDK File
        run: |
          echo "${{ secrets.FIREBASE_ADMIN_SDK_TEST }}" > "${{ secrets.FIREBASE_ADMIN_SDK_FILENAME_TEST }}"
          
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest -s -vv test_jajal.py
